### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by cemcevik** [robertcash/RCEasySpotifyRipper.py#2]
What is the difference between spotify-ripper and this one ?

They are downloading song as same speed.

**Comment by robertcash** [comment]
Hi,

I made this as an easy way for myself to enter a bunch of urls in a text file to download in mass without doing one at a time in a command prompt manually. Speed isn't the point of this, i just shared it because I thought someone might find use of an easy setup (spotify-ripper didn't have a easy setup at the time) and mass track downloading on top of a complicated thing to setup. Please don't open an issue if there's no issue.

Thanks,

Robert
